### Crear varias obras de arte usando REST Client

# Crear obra 1
POST https://h8rtvvc7-3000.use2.devtunnels.ms/artworks/upload
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="image"

https://example.com/path/to/obra1.jpg
--boundary
Content-Disposition: form-data; name="userId"

1
--boundary
Content-Disposition: form-data; name="price"

1000
--boundary--

### Crear obra 2
POST https://h8rtvvc7-3000.use2.devtunnels.ms/artworks/upload
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="image"

https://example.com/path/to/obra2.jpg
--boundary
Content-Disposition: form-data; name="userId"

1
--boundary
Content-Disposition: form-data; name="price"

2000
--boundary--

### Crear obra 3
POST https://h8rtvvc7-3000.use2.devtunnels.ms/artworks/upload
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="image"

https://example.com/path/to/obra3.jpg
--boundary
Content-Disposition: form-data; name="userId"

1
--boundary
Content-Disposition: form-data; name="price"

3000
--boundary--
